### ISSUE TITLE
not finding the images

### ISSUE THREAD

**Issue by harichandu13** [IBM/image-classification-using-cnn-and-keras#16]
train_path = 'D:\data\Train_Data'
train_batches = ImageDataGenerator().flow_from_directory(train_path, target_size=(10,10), classes=classes_required, batch_size=50,class_mode='binary')
type(train_batches)

Found 0 images belonging to 106 classes.

**Comment by smruthi33** [comment]
Hi @harichandu13, I can see that you have 106 classes. Could you pls confirm that you have updated the field `classes_required` with your classes. If not pls refer the documentation and code to make changes on the same.
