### ISSUE TITLE
Watson Studio Python is version 6.7, Keras is not supported

### ISSUE THREAD

**Issue by omoralesm** [IBM/image-classification-using-cnn-and-keras#18]
Hi, I am trying to run the code, but the current Python version in Watson Studio is 6.7, it seems that Keras is not supported, do you know if there is a workaround? Thanks a lot.
![KerasNotFound](https://user-images.githubusercontent.com/15077989/127581820-03d078ef-fb91-4891-9a54-40f4eec933dd.png)

**Comment by muralidharchavan** [comment]
Hi. Before importing keras, please include the line `!pip install keras` to install keras.

**Comment by omoralesm** [comment]
Hi, 

Thanks a lot, this solves de installation issue.
